namespace PackShaders;

/// <summary>Function to generate C# enum to identify shaders</summary>
static class ShaderNames
{
	/// <summary>Generate C# enum to identify shaders, write to the specified <c>*.cs</c> path</summary>
	public static void write( string path, string[] names )
	{
		using var w = File.CreateText( path );
		w.WriteLine( @"// This source file is generated by PackShaders.exe tool" );
		w.WriteLine( "namespace {0};", Program.inputs.ns );
		w.WriteLine( @"
enum eShader: ushort
{" );
		for( int i = 0; i < names.Length; i++ )
			w.WriteLine( "\t{0} = {1},", names[ i ], i );

		w.Write( "}" );
	}
}