namespace MistralChat;
using MistralChat.ViewModels;
using System.Windows;
using System.Windows.Controls;

/// <summary>Utility class to select data templates for chat log entries</summary>
public sealed class ChatLogTemplateSelector: DataTemplateSelector
{
	/// <summary>Data template for messages written by user</summary>
	public DataTemplate? user { get; set; }

	/// <summary>Data template for messages generated by computer</summary>
	public DataTemplate? computer { get; set; }

	public override DataTemplate? SelectTemplate( object item, DependencyObject container )
	{
		if( item is iChatMessageVM message )
			return message.user ? user : computer;

		return null;
	}
}